FROM openjdk:17-slim

# Set working directory
WORKDIR /app

# Copy the fat jar created by maven-shade-plugin
COPY target/p2p-1.0-SNAPSHOT-shaded.jar app.jar

# Expose the backend port
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "app.jar"]
